name: Build AbzzModz

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show project files
        shell: powershell
        run: |
          Write-Host "===== REPOSITORY ====="
          Get-ChildItem -Recurse | Select-Object FullName

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build AbzzModz
        shell: powershell
        run: |
          msbuild .\AbzzModz.vcxproj `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /verbosity:normal
